# Generated by Django 3.2.6 on 2021-08-05 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('accepts_terms', models.BooleanField()),
                ('terms_accepted', models.CharField(default='1.0.0', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
